import Link from "next/link";
import '../../styles/Home.module.css'
import Head from 'next/head'

const Blog = () => {
    return (
        <div className="container">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Link href='/'><button>home</button></Link>
        </div>
    )
}

export default Blog;